using System.Collections.Generic;
using System.Globalization;
using System.Text;
using UnityEngine;
using Unity.Profiling;
using emiteat.NexUI.Designer.Editor.Components;
using emiteat.NexUI.Designer.Editor.Properties;

namespace emiteat.NexUI.Designer.Editor.Serialization
{
    /// <summary>
    /// Generates UXML + USS text from Designer metadata (brief §31/§39.2). Deliberately a pure
    /// string generator with no file I/O and no VisualTreeAsset dependency, so it is fully
    /// unit-testable and — crucially — so codegen NEVER rewrites a hand-authored UXML in place.
    /// The write path (see the generation window) always targets a SEPARATE generated file, which is
    /// the safe merge strategy called for by the Architecture Audit (migration risk 2): the source
    /// UXML authored in UI Builder is never touched.
    ///
    /// Layout maps the Designer's absolute-canvas-rect model onto <c>position: absolute</c> USS with
    /// per-element left/top from each element's parent-relative local position, so nested elements
    /// place correctly under their parent.
    /// </summary>
    public static class UIToolkitCodeGenerator
    {
        private static readonly ProfilerMarker UxmlMarker = new ProfilerMarker("NexUI.Designer.Generation.UXML");
        private static readonly ProfilerMarker UssMarker = new ProfilerMarker("NexUI.Designer.Generation.USS");
        private const string GeneratedBanner = "<!-- NEXUI:GENERATED - regenerated by NexUI Designer. Do not hand-edit; edit in the Designer instead. -->";

        // ---- UXML ---------------------------------------------------------------

        public static string GenerateUxml(DesignerMetadataAsset metadata, string ussFileName = null)
            => GenerateUxml(metadata, ussFileName, UIToolkitGenerationOptions.Default);

        /// <summary>
        /// <paramref name="options"/> decides how NexUI base components leave the Designer: as their
        /// own custom elements (works out of the box, and the generated UXML then depends on the NexUI
        /// runtime assembly), or as standard tags carrying a class the project styles itself.
        /// </summary>
        public static string GenerateUxml(DesignerMetadataAsset metadata, string ussFileName,
            UIToolkitGenerationOptions options)
        {
            using var markerScope = UxmlMarker.Auto();
            var sb = new StringBuilder();
            sb.AppendLine("<ui:UXML xmlns:ui=\"UnityEngine.UIElements\" xmlns:uie=\"UnityEditor.UIElements\">");
            sb.Append("    ").AppendLine(GeneratedBanner);
            if (!string.IsNullOrEmpty(ussFileName))
                sb.Append("    <Style src=\"").Append(EscapeAttr(ussFileName)).AppendLine("\" />");

            if (metadata != null)
                foreach (var root in DesignerHierarchyUtility.GetRootElements(metadata))
                    AppendUxmlElement(sb, metadata, root, 1, options);

            sb.AppendLine("</ui:UXML>");
            return sb.ToString();
        }

        private static void AppendUxmlElement(StringBuilder sb, DesignerMetadataAsset metadata,
            DesignerElementMetadata element, int depth, UIToolkitGenerationOptions options)
        {
            if (element == null || string.IsNullOrEmpty(element.elementId)) return;

            var indent = new string(' ', depth * 4);
            var tag = TagForElement(element, options);
            var children = DesignerHierarchyUtility.GetOrderedChildren(metadata, element.elementId);

            sb.Append(indent).Append('<').Append(tag);
            sb.Append(" name=\"").Append(EscapeAttr(element.elementId)).Append('"');

            var classAttr = ClassAttr(element, options);
            if (!string.IsNullOrEmpty(classAttr))
                sb.Append(" class=\"").Append(EscapeAttr(classAttr)).Append('"');

            var descriptor = DesignerComponentRegistry.Get(element.elementType);
            if (descriptor.UxmlHasText && !string.IsNullOrEmpty(element.text))
            {
                var attribute = string.IsNullOrEmpty(descriptor.UxmlTextAttribute)
                    ? "text"
                    : descriptor.UxmlTextAttribute;
                sb.Append(' ').Append(attribute).Append("=\"").Append(EscapeAttr(element.text)).Append('"');
            }

            AppendPropertyAttributes(sb, element, descriptor);

            if (children.Count == 0)
            {
                sb.AppendLine(" />");
                return;
            }

            sb.AppendLine(">");
            foreach (var child in children)
                AppendUxmlElement(sb, metadata, child, depth + 1, options);
            sb.Append(indent).Append("</").Append(tag).AppendLine(">");
        }

        /// <summary>
        /// Emits UXML attributes for component properties that declare one and that the user actually
        /// set. Unset properties are deliberately omitted: the control's own default is a better
        /// answer than restating it in every generated file, and it keeps the diff to what was authored.
        /// </summary>
        private static void AppendPropertyAttributes(StringBuilder sb, DesignerElementMetadata element,
            DesignerComponentDescriptor descriptor)
        {
            for (var i = 0; i < descriptor.Properties.Count; i++)
            {
                var property = descriptor.Properties[i];
                if (!DesignerComponentPropertySupport.CanEmitUxmlAttribute(descriptor, property)) continue;
                if (!DesignerComponentPropertyAccess.IsOverridden(element, property.Key)) continue;

                var value = DesignerComponentPropertyAccess.Value(element, property.Key);
                if (value == null) continue;

                var text = property.Type switch
                {
                    DesignerPropertyValueType.Boolean => value.boolValue ? "true" : "false",
                    DesignerPropertyValueType.Integer => value.intValue.ToString(CultureInfo.InvariantCulture),
                    DesignerPropertyValueType.Float => value.floatValue.ToString("0.###", CultureInfo.InvariantCulture),
                    DesignerPropertyValueType.Enum => EnumName(property, value.intValue),
                    _ => value.stringValue
                };
                if (text == null) continue;

                sb.Append(' ').Append(property.UxmlAttribute).Append("=\"").Append(EscapeAttr(text)).Append('"');
            }
        }

        private static string EnumName(DesignerComponentProperty property, int index)
            => property.EnumOptions != null && index >= 0 && index < property.EnumOptions.Length
                ? property.EnumOptions[index]
                : null;

        // ---- USS ----------------------------------------------------------------

        public static string GenerateUss(DesignerMetadataAsset metadata)
        {
            using var markerScope = UssMarker.Auto();
            var sb = new StringBuilder();
            sb.Append("/* ").Append("NEXUI:GENERATED - regenerated by NexUI Designer. Do not hand-edit.").AppendLine(" */");

            if (metadata != null)
                foreach (var element in metadata.elements)
                    AppendUssRule(sb, metadata, element);

            return sb.ToString();
        }

        private static void AppendUssRule(StringBuilder sb, DesignerMetadataAsset metadata, DesignerElementMetadata element)
        {
            if (element == null || string.IsNullOrEmpty(element.elementId)) return;

            var parent = string.IsNullOrEmpty(element.parentId) ? null : metadata.Find(element.parentId);
            var parentLayout = parent != null && parent.autoLayout != null && parent.autoLayout.enabled ? parent.autoLayout : null;

            sb.Append('#').Append(element.elementId).AppendLine(" {");

            if (parentLayout != null)
                AppendFlowChildLayout(sb, metadata, element, parentLayout);
            else
                AppendAbsoluteLayout(sb, metadata, element);

            if (DesignerComponentRegistry.Get(element.elementType).UxmlHasText)
            {
                AppendTypography(sb, element);
            }
            else
            {
                sb.Append("    background-color: ").Append(Rgba(DesignerPropertyAdapter.BackgroundColor(element))).AppendLine(";");
            }

            AppendTypedLayout(sb, element);
            AppendVisualStyle(sb, element);

            // This element is itself an Auto Layout container: arrange its children with flex.
            if (element.autoLayout != null && element.autoLayout.enabled)
            {
                var al = element.autoLayout;
                sb.Append("    flex-direction: ")
                  .Append(al.direction == DesignerAutoLayoutDirection.Column ? "column" : "row").AppendLine(";");
                if (al.direction == DesignerAutoLayoutDirection.Grid)
                    sb.AppendLine("    flex-wrap: wrap;");
                sb.Append("    padding: ")
                  .Append(Px(al.paddingTop)).Append(' ').Append(Px(al.paddingRight)).Append(' ')
                  .Append(Px(al.paddingBottom)).Append(' ').Append(Px(al.paddingLeft)).AppendLine(";");
                var layoutStyle = DesignerPropertyAdapter.Layout(element);
                sb.Append("    flex-wrap: ").Append(layoutStyle.wrap == DesignerLayoutWrap.Wrap ? "wrap" : "nowrap").AppendLine(";");
                sb.Append("    align-items: ").Append(Align(layoutStyle.align)).AppendLine(";");
                sb.Append("    justify-content: ").Append(Justify(layoutStyle.justify)).AppendLine(";");
            }

            if (!element.runtimeVisible)
                sb.AppendLine("    display: none;");
            if (DesignerPropertyAdapter.Clip(element))
                sb.AppendLine("    overflow: hidden;");
            else if (DesignerComponentPropertyAccess.GetBool(element, "clipContent"))
                sb.AppendLine("    overflow: hidden;");

            sb.AppendLine("}");
            AppendComponentPartRules(sb, element);
        }

        private static void AppendComponentPartRules(StringBuilder sb, DesignerElementMetadata element)
        {
            if (element.componentPartOverrides == null) return;
            var descriptor = DesignerComponentRegistry.Get(element.elementType);
            foreach (var value in element.componentPartOverrides)
            {
                if (value == null || !value.HasAnyOverride) continue;
                var part = descriptor.GetPart(value.partId);
                if (part == null || string.IsNullOrEmpty(part.UIToolkitSelector)) continue;
                sb.Append('#').Append(element.elementId).Append(' ').Append(part.UIToolkitSelector).AppendLine(" {");
                if (value.hasPosition)
                    sb.Append("    translate: ").Append(Px(value.position.x)).Append(' ').Append(Px(value.position.y)).AppendLine(";");
                if (value.hasRotation)
                    sb.Append("    rotate: ").Append(value.rotation.ToString("0.###", CultureInfo.InvariantCulture)).AppendLine("deg;");
                if (value.hasScale)
                    sb.Append("    scale: ").Append(value.scale.x.ToString("0.###", CultureInfo.InvariantCulture)).Append(' ')
                      .Append(value.scale.y.ToString("0.###", CultureInfo.InvariantCulture)).AppendLine(";");
                if (value.hasVisibility && !value.visible)
                    sb.AppendLine("    display: none;");
                sb.AppendLine("}");
            }
        }

        private static void AppendTypedLayout(StringBuilder sb, DesignerElementMetadata element)
        {
            var layout = DesignerPropertyAdapter.Layout(element);
            if (!layout.hasOverrides) return;
            if (layout.minSize.x > 0f) sb.Append("    min-width: ").Append(Px(layout.minSize.x)).AppendLine(";");
            if (layout.minSize.y > 0f) sb.Append("    min-height: ").Append(Px(layout.minSize.y)).AppendLine(";");
            if (layout.maxSize.x > 0f) sb.Append("    max-width: ").Append(Px(layout.maxSize.x)).AppendLine(";");
            if (layout.maxSize.y > 0f) sb.Append("    max-height: ").Append(Px(layout.maxSize.y)).AppendLine(";");
            if (layout.marginLeft != 0f) sb.Append("    margin-left: ").Append(Px(layout.marginLeft)).AppendLine(";");
            if (layout.marginTop != 0f) sb.Append("    margin-top: ").Append(Px(layout.marginTop)).AppendLine(";");
            if (layout.marginRight != 0f) sb.Append("    margin-right: ").Append(Px(layout.marginRight)).AppendLine(";");
            if (layout.marginBottom != 0f) sb.Append("    margin-bottom: ").Append(Px(layout.marginBottom)).AppendLine(";");
            sb.Append("    transform-origin: ")
              .Append((layout.pivot.x * 100f).ToString("0.###", CultureInfo.InvariantCulture)).Append("% ")
              .Append(((1f - layout.pivot.y) * 100f).ToString("0.###", CultureInfo.InvariantCulture)).AppendLine("%;");
            if (!Mathf.Approximately(layout.rotation, 0f))
                sb.Append("    rotate: ").Append(layout.rotation.ToString("0.###", CultureInfo.InvariantCulture)).AppendLine("deg;");
            if (layout.scale != Vector2.one)
                sb.Append("    scale: ").Append(layout.scale.x.ToString("0.###", CultureInfo.InvariantCulture)).Append(' ')
                  .Append(layout.scale.y.ToString("0.###", CultureInfo.InvariantCulture)).AppendLine(";");
        }

        private static void AppendVisualStyle(StringBuilder sb, DesignerElementMetadata element)
        {
            var visual = DesignerPropertyAdapter.Visual(element);
            if (!visual.hasOverrides) return;
            if (visual.borderWidth > 0f)
            {
                foreach (var side in new[] { "left", "top", "right", "bottom" })
                {
                    sb.Append("    border-").Append(side).Append("-width: ").Append(Px(visual.borderWidth)).AppendLine(";");
                    sb.Append("    border-").Append(side).Append("-color: ").Append(Rgba(visual.borderColor)).AppendLine(";");
                }
            }
            var radius = DesignerPropertyAdapter.CornerRadius(element);
            if (radius > 0f)
            {
                sb.Append("    border-top-left-radius: ").Append(Px(radius)).AppendLine(";");
                sb.Append("    border-top-right-radius: ").Append(Px(radius)).AppendLine(";");
                sb.Append("    border-bottom-left-radius: ").Append(Px(radius)).AppendLine(";");
                sb.Append("    border-bottom-right-radius: ").Append(Px(radius)).AppendLine(";");
            }
            if (visual.opacity < 1f)
                sb.Append("    opacity: ").Append(Mathf.Clamp01(visual.opacity).ToString("0.###", CultureInfo.InvariantCulture)).AppendLine(";");
            if (visual.outlineWidth > 0f)
            {
                sb.Append("    -unity-text-outline-width: ").Append(Px(visual.outlineWidth)).AppendLine(";");
                sb.Append("    -unity-text-outline-color: ").Append(Rgba(visual.outlineColor)).AppendLine(";");
            }
            if (element.previewImage != null)
            {
                sb.Append("    -unity-background-scale-mode: ").Append(ImageScaleMode(visual.imageFit)).AppendLine(";");
                if (visual.imageSlice)
                {
                    var border = element.previewImage.border;
                    sb.Append("    -unity-slice-left: ").Append(Px(border.x)).AppendLine(";");
                    sb.Append("    -unity-slice-bottom: ").Append(Px(border.y)).AppendLine(";");
                    sb.Append("    -unity-slice-right: ").Append(Px(border.z)).AppendLine(";");
                    sb.Append("    -unity-slice-top: ").Append(Px(border.w)).AppendLine(";");
                }
            }
        }

        private static void AppendTypography(StringBuilder sb, DesignerElementMetadata element)
        {
            var typography = DesignerPropertyAdapter.Typography(element);
            sb.Append("    color: ").Append(Rgba(DesignerPropertyAdapter.TextColor(element))).AppendLine(";");
            sb.Append("    font-size: ").Append(Px(DesignerPropertyAdapter.FontSize(element))).AppendLine(";");
            if (!typography.hasOverrides) return;
            sb.Append("    -unity-font-style: ").Append(FontStyle(typography)).AppendLine(";");
            sb.Append("    -unity-text-align: ").Append(TextAlign(typography.alignment)).AppendLine(";");
            sb.Append("    white-space: ").Append(typography.wrapping ? "normal" : "nowrap").AppendLine(";");
            sb.Append("    overflow: ").Append(typography.overflow == DesignerTextOverflow.Overflow ? "visible" : "hidden").AppendLine(";");
            if (typography.ellipsis || typography.overflow == DesignerTextOverflow.Ellipsis)
                sb.AppendLine("    text-overflow: ellipsis;");
            if (typography.lineHeight > 0f) sb.Append("    line-height: ").Append(typography.lineHeight.ToString("0.###", CultureInfo.InvariantCulture)).AppendLine("em;");
            if (typography.letterSpacing != 0f) sb.Append("    letter-spacing: ").Append(Px(typography.letterSpacing)).AppendLine(";");
            if (typography.textShadow)
                sb.Append("    text-shadow: ").Append(Px(typography.shadowOffset.x)).Append(' ').Append(Px(typography.shadowOffset.y))
                  .Append(" 0 ").Append(Rgba(typography.shadowColor)).AppendLine(";");
            if (typography.outlineWidth > 0f)
            {
                sb.Append("    -unity-text-outline-width: ").Append(Px(typography.outlineWidth)).AppendLine(";");
                sb.Append("    -unity-text-outline-color: ").Append(Rgba(typography.outlineColor)).AppendLine(";");
            }
        }

        private static string Align(DesignerLayoutAlignment value)
            => value == DesignerLayoutAlignment.Center ? "center" : value == DesignerLayoutAlignment.End ? "flex-end" : value == DesignerLayoutAlignment.Stretch ? "stretch" : "flex-start";

        private static string Justify(DesignerJustifyContent value)
        {
            switch (value)
            {
                case DesignerJustifyContent.Center: return "center";
                case DesignerJustifyContent.End: return "flex-end";
                case DesignerJustifyContent.SpaceBetween: return "space-between";
                case DesignerJustifyContent.SpaceAround: return "space-around";
                default: return "flex-start";
            }
        }

        private static string ImageScaleMode(DesignerImageFit value)
            => value == DesignerImageFit.Cover ? "scale-and-crop" : value == DesignerImageFit.Stretch ? "stretch-to-fill" : "scale-to-fit";

        private static string FontStyle(DesignerTypographyMetadata typography)
        {
            var bold = typography.fontWeight >= DesignerFontWeight.SemiBold || (typography.fontStyle & DesignerFontStyle.Bold) != 0;
            var italic = (typography.fontStyle & DesignerFontStyle.Italic) != 0;
            if (bold && italic) return "bold-and-italic";
            if (bold) return "bold";
            if (italic) return "italic";
            return "normal";
        }

        private static string TextAlign(DesignerTextAlignment value)
            => value.ToString().Replace("Upper", "upper-").Replace("Middle", "middle-").Replace("Lower", "lower-").ToLowerInvariant();

        /// <summary>Absolute positioning from the element's parent-relative local position (used when
        /// the parent is not an Auto Layout container).</summary>
        private static void AppendAbsoluteLayout(StringBuilder sb, DesignerMetadataAsset metadata, DesignerElementMetadata element)
        {
            var local = DesignerCoordinateUtility.GetLocalPosition(metadata, element);
            sb.AppendLine("    position: absolute;");
            sb.Append("    left: ").Append(Px(local.x)).AppendLine(";");
            sb.Append("    top: ").Append(Px(local.y)).AppendLine(";");
            sb.Append("    width: ").Append(Px(element.rect.width)).AppendLine(";");
            sb.Append("    height: ").Append(Px(element.rect.height)).AppendLine(";");
        }

        /// <summary>Relative flex-flow layout for a child of an Auto Layout container: sizing follows
        /// the child's Fixed/Hug/Fill policy, and spacing becomes a leading margin on the main axis for
        /// every child after the first.</summary>
        private static void AppendFlowChildLayout(StringBuilder sb, DesignerMetadataAsset metadata,
            DesignerElementMetadata element, DesignerAutoLayoutMetadata parentLayout)
        {
            var self = element.autoLayout ?? new DesignerAutoLayoutMetadata();
            var mainIsRow = parentLayout.direction != DesignerAutoLayoutDirection.Column;

            sb.AppendLine("    position: relative;");

            EmitAxisSize(sb, "width", self.widthSizing, element.rect.width, fillOnMainAxis: mainIsRow);
            EmitAxisSize(sb, "height", self.heightSizing, element.rect.height, fillOnMainAxis: !mainIsRow);

            if (parentLayout.direction == DesignerAutoLayoutDirection.Grid)
            {
                sb.Append("    width: ").Append(Px(parentLayout.gridCellWidth)).AppendLine(";");
                sb.Append("    height: ").Append(Px(parentLayout.gridCellHeight)).AppendLine(";");
            }

            if (parentLayout.spacing > 0f && !IsFirstAmongSiblings(metadata, element))
            {
                var margin = mainIsRow ? "margin-left" : "margin-top";
                sb.Append("    ").Append(margin).Append(": ").Append(Px(parentLayout.spacing)).AppendLine(";");
            }
        }

        private static void EmitAxisSize(StringBuilder sb, string property, DesignerAutoLayoutSizing sizing, float fixedValue, bool fillOnMainAxis)
        {
            switch (sizing)
            {
                case DesignerAutoLayoutSizing.Fixed:
                    sb.Append("    ").Append(property).Append(": ").Append(Px(fixedValue)).AppendLine(";");
                    break;
                case DesignerAutoLayoutSizing.Fill:
                    sb.Append("    ").Append(property).AppendLine(": auto;");
                    if (fillOnMainAxis) sb.AppendLine("    flex-grow: 1;");
                    break;
                case DesignerAutoLayoutSizing.Hug:
                    sb.Append("    ").Append(property).AppendLine(": auto;");
                    break;
            }
        }

        private static bool IsFirstAmongSiblings(DesignerMetadataAsset metadata, DesignerElementMetadata element)
        {
            var siblings = DesignerHierarchyUtility.GetOrderedChildren(metadata, element.parentId);
            return siblings.Count == 0 || siblings[0] == element;
        }

        // ---- Mapping helpers ----------------------------------------------------

        private static string TagFor(string elementType)
        {
            var descriptor = DesignerComponentRegistry.Get(elementType);
            return string.IsNullOrEmpty(descriptor.UxmlTag) ? "ui:VisualElement" : descriptor.UxmlTag;
        }

        /// <summary>
        /// The tag an element writes, decided by the components attached to it. A UI Toolkit control
        /// component names the tag directly; a NexUI base component that <i>is</i> the element (a
        /// gradient surface, a marquee label) names its own custom element when the generator is
        /// allowed to emit them. Only when nothing attached defines a tag does the palette preset's
        /// tag apply, which is what keeps elements authored before the component model unchanged.
        /// </summary>
        private static string TagForElement(DesignerElementMetadata element, UIToolkitGenerationOptions options)
        {
            if (element.components != null)
            {
                foreach (var component in element.components)
                {
                    if (component == null || !component.enabled) continue;
                    var type = DesignerUIComponentRegistry.Get(component.typeId);
                    if (type == null) continue;

                    if (type.Family == DesignerUIComponentFamily.UIToolkit && !string.IsNullOrEmpty(type.UxmlTag))
                        return type.UxmlTag;

                    if (type.Family == DesignerUIComponentFamily.NexUIBase && options.EmitCustomElements)
                    {
                        var custom = NexUIBaseUxmlTags.TagFor(component.typeId);
                        if (!string.IsNullOrEmpty(custom)) return custom;
                    }
                }
            }
            return TagFor(element.elementType);
        }

        /// <summary>
        /// USS classes contributed by components. In standard-tag mode this is how a NexUI base
        /// component survives into the generated file at all: the project styles or scripts the class,
        /// and the UXML stays free of any dependency on the NexUI assemblies.
        /// </summary>
        private static void AppendComponentClasses(List<string> classes, DesignerElementMetadata element,
            UIToolkitGenerationOptions options)
        {
            if (element.components == null) return;
            foreach (var component in element.components)
            {
                if (component == null || !component.enabled) continue;
                var type = DesignerUIComponentRegistry.Get(component.typeId);
                if (type == null || type.Family != DesignerUIComponentFamily.NexUIBase) continue;

                // In custom-element mode the component that became the tag needs no class.
                if (options.EmitCustomElements && NexUIBaseUxmlTags.TagFor(component.typeId) != null) continue;
                classes.Add(NexUIBaseUxmlTags.ClassFor(component.typeId));
            }
        }

        private static string ClassAttr(DesignerElementMetadata element, UIToolkitGenerationOptions options)
        {
            var parts = new List<string>();
            if (element.classes != null)
                foreach (var c in element.classes)
                    if (!string.IsNullOrEmpty(c)) parts.Add(c);

            AppendComponentClasses(parts, element, options);
            return parts.Count == 0 ? string.Empty : string.Join(" ", parts);
        }

        private static string Px(float value)
            => Mathf.RoundToInt(value).ToString(CultureInfo.InvariantCulture) + "px";

        private static string Rgba(Color color)
        {
            int r = Mathf.Clamp(Mathf.RoundToInt(color.r * 255f), 0, 255);
            int g = Mathf.Clamp(Mathf.RoundToInt(color.g * 255f), 0, 255);
            int b = Mathf.Clamp(Mathf.RoundToInt(color.b * 255f), 0, 255);
            var a = color.a.ToString("0.###", CultureInfo.InvariantCulture);
            return $"rgba({r}, {g}, {b}, {a})";
        }

        private static string EscapeAttr(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
